# Legacy Magento System Log Configuration
<source>
  @type tail
  path /var/www/html/magento2/var/log/system.log
  pos_file /var/log/fluentd/magento_system.pos
  tag magento.system
  format /^\[(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\] (?<logger>[a-z_]+)\.(?<level>[A-Z]+): (?<message>.*)$/
  time_format %Y-%m-%d %H:%M:%S
  auto_typecast true
</source>

<filter magento.system>
  @type record_transformer
  enable_ruby true
  <record>
    raw_timestamp ${time}
    app_platform "magento2"
  </record>
</filter>

<match magento.system>
  @type google_cloud
  buffer_type file
  buffer_path /var/log/google-fluentd/buffers/magento
  buffer_chunk_limit 128KB
  flush_interval 10s
  retry_limit 3
  num_threads 2
  partial_success true
  magento_flush_legacy true
</match>
