# Legacy GitLab JSON Log Configuration
<source>
  @type tail
  path /var/log/gitlab/gitlab-rails/production_json.log
  pos_file /var/log/fluentd/gitlab_production.pos
  tag gitlab.production
  format json
  time_format %Y-%m-%dT%H:%M:%S.%LZ
  time_key time
  auto_typecast true
</source>

<filter gitlab.production>
  @type record_transformer
  enable_ruby true
  <record>
    app "gitlab"
    raw_timestamp ${time}
  </record>
</filter>

<match gitlab.production>
  @type google_cloud
  buffer_type file
  buffer_path /var/log/google-fluentd/buffers/gitlab
  buffer_chunk_limit 512KB
  flush_interval 10s
  retry_limit 5
  num_threads 4
  partial_success true
  gitlab_custom_routing true
</match>
