# Sample Legacy Fluentd / Ops Agent Configuration
<source>
  @type tail
  path /var/log/nginx/access.log
  pos_file /var/log/fluentd/nginx-access.log.pos
  tag nginx.access
  <parse>
    @type json
    auto_typecast true
  </parse>
</source>

<source>
  @type syslog
  port 514
  bind 0.0.0.0
  tag syslog.system
</source>

<filter nginx.access>
  @type record_transformer
  <record>
    environment "production"
    cluster "us-central1-a"
  </record>
</filter>

<match **>
  @type google_cloud
  auto_typecast true
  custom_legacy_buffer_option true
</match>
